version: '3.8'
services:
    database:
        image: postgres:latest
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - '5432:5432'
        volumes:
            - database:/var/lib/postgresql/data

    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        volumes:
            - .:/app
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            PHP_IDE_CONFIG: serverName=Docker
        depends_on:
            - database

    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./public:/app/public
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php
volumes:
    database:
